// E2E Testing on Edge — generated by tech-tree
import { expect, test } from "@playwright/test";

const BASE = process.env.DEPLOY_URL || "http://localhost:8787";

test("deploy and verify", async ({ page }) => {
	await page.goto(BASE);
	await expect(page.locator("h1")).toBeVisible();
});
